# Generated by Django 5.2.5 on 2026-03-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("total_seats", models.IntegerField()),
                ("available_seats", models.IntegerField()),
            ],
        ),
    ]
